.TH Spot-On-Lite-Daemon 1 "February 21, 2018"
.SH NAME
Spot-On-Lite-Daemon
.SH SYNOPSIS
.B Spot-On-Lite-Daemon [options]
.SH DESCRIPTION
.B Spot-On-Lite-Daemon
is an extremely lite version of Spot-On.
.SH OPTIONS
.TP
.BI --configuration-file " file"
Absolute path of the configuration file. Only the first instance will be considered.
.TP
.BI --help
Display helpful text.
.TP
.BI --validate-configuration-file " file"
Validate the specified configuration file. Only the first instance will be considered.
.SH NOTES
None.
.SH AUTHOR(S)
.B Alexis Megas
